apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - pedersen.io
      - www.pedersen.io
      - jenkins.pedersen.io
      - derek.pedersen.io
      - jasper.pedersen.io
      - marissa.pedersen.io
      secretName: pedersen-io-tls
    - hosts:
      - celebrityskateboards.com
      - www.celebrityskateboards.com
      secretName: celebrityskateboards-tls
    - hosts:
      - pedersen.app
      secretName: pedersen-app-tls
  rules:
  - host: pedersen.app
    http:
      paths:
        - backend:
            serviceName: video-playback-server
            servicePort: 8080
          path: /video-playback
  - host: pedersen.io
    http:
      paths:
      - backend:
          serviceName: skatepark-api
          servicePort: 8080
        path: /api/skateparks
      - backend:
          serviceName: dp-spa-vue-test
          servicePort: 80
        path: /
  - host: www.pedersen.io
    http:
      paths:
      - backend:
          serviceName: skatepark-api
          servicePort: 8080
        path: /api/skateparks
      - backend:
          serviceName: dp-spa-vue-test
          servicePort: 80
        path: /
  - host: jenkins.pedersen.io
    http:
      paths:
      - backend:
          serviceName: jenkins-1578171870
          servicePort: 8080
        path: /
  - host: derek.pedersen.io
    http:
      paths:
      - backend:
          serviceName: dp-spa-angular
          servicePort: 80
        path: /
      - backend:
          serviceName: resume-api-dotnetcore
          servicePort: 80
        path: /api
  - host: jasper.pedersen.io
    http:
      paths:
      - backend:
          serviceName: jp-spa-react
          servicePort: 80
        path: /
  - host: marissa.pedersen.io
    http:
      paths:
      - backend:
          serviceName: jp-spa-react
          servicePort: 80
        path: /
  - host: celebrityskateboards.com
    http:
      paths:
      - backend:
          serviceName: skatepark-api
          servicePort: 8080
        path: /api/skateparks
      - backend:
          serviceName: celebrityskateboards
          servicePort: 80
        path: /
  - host: www.celebrityskateboards.com
    http:
      paths:
      - backend:
          serviceName: skatepark-api
          servicePort: 8080
        path: /api/skateparks
      - backend:
          serviceName: celebrityskateboards
          servicePort: 80
        path: /
