apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "pedersensoftware-dot-com"
  labels:
    stable.k8s.psg.io/kcm.class: "default"
spec:
  domain: "pedersensoftware.com"
  email: "derekpedersen.contact@gmail.com"
  provider: "googlecloud"
  secretName: pedersensoftware-dot-com
  altNames:
    - "www.pedersensoftware.com"