apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "jupyter-derekpedersen-dot-io"
  labels:
    stable.k8s.psg.io/kcm.class: "default"
spec:
  domain: "jupyter.derekpedersen.io"
  email: "derekpedersen.contact@gmail.com"
  provider: "googlecloud"
  secretName: jupyter-derekpedersen-dot-io
  altNames:
    - "jupyter.derekpedersen.io"