apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-proxy-deployment
  name: nginx-proxy-service
  namespace: default
spec:
  ports:
  - name: 80-to-80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-to-443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-proxy-deployment
  type: LoadBalancer